steps:
  - name: 'node:16.19'
    script: |
      #!/usr/bin/env bash
      cd app/rts
      yarn build
      cd ../client
      yarn install
      yarn build
  - name: gcr.io/cloud-builders/mvn
    script: |
      #!/usr/bin/env bash
      apt-get update
      apt-get upgrade --yes
      apt-get install --no-install-recommends --yes rsync
      cd app/server
      mvn -B clean compile
      ./build.sh -DskipTests
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - 'gcr.io/$PROJECT_ID/$BRANCH_NAME:$SHORT_SHA'
      - .
images:
  - 'gcr.io/$PROJECT_ID/$BRANCH_NAME:$SHORT_SHA'
options:
  machineType: E2_HIGHCPU_32
